import { StyleSheet } from 'react-native';
import { spacing, typography, borderRadius } from '../../../theme/tokens';
import type { ThemeColors } from '../../../contexts/theme-colors';

export const createStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    safeArea: { flex: 1 },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    backButton: { width: 44, height: 44, justifyContent: 'center', alignItems: 'center' },
    headerTitle: { ...typography.h4, color: colors.textPrimary },
    content: { flex: 1, paddingHorizontal: spacing.lg },
    section: { marginTop: spacing.lg },
    sectionTitle: { ...typography.h4, color: colors.textPrimary, marginBottom: spacing.xs },
    sectionHint: { ...typography.bodySmall, color: colors.textSecondary, marginBottom: spacing.md },
    photoGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
    photoSlot: {
      width: '31%',
      aspectRatio: 1,
      backgroundColor: colors.surface,
      borderRadius: borderRadius.lg,
      borderWidth: 2,
      borderStyle: 'dashed',
      borderColor: colors.border,
      justifyContent: 'center',
      alignItems: 'center',
      overflow: 'hidden',
    },
    primaryPhotoSlot: { borderColor: colors.primary },
    photoImage: { width: '100%', height: '100%' },
    photoRemove: {
      position: 'absolute',
      top: 8,
      right: 8,
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: colors.error,
      justifyContent: 'center',
      alignItems: 'center',
    },
    primaryLabel: { ...typography.bodySmall, color: colors.primary, marginTop: 4 },
    fieldLabel: {
      ...typography.label,
      color: colors.textSecondary,
      marginBottom: spacing.sm,
      textTransform: 'uppercase',
    },
    input: {
      backgroundColor: colors.surface,
      borderRadius: borderRadius.md,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.md,
      ...typography.body,
      color: colors.textPrimary,
    },
    bioInput: { height: 120, paddingTop: spacing.md },
    charCount: {
      ...typography.bodySmall,
      color: colors.textTertiary,
      textAlign: 'right',
      marginTop: spacing.xs,
    },
    optionGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
    optionButton: {
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
      borderRadius: borderRadius.full,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
    },
    optionButtonSelected: { backgroundColor: colors.primary, borderColor: colors.primary },
    optionText: { ...typography.body, color: colors.textPrimary },
    optionTextSelected: { color: colors.white },
    optionRow: { flexDirection: 'row', gap: spacing.sm },
    styleButton: {
      flex: 1,
      paddingVertical: spacing.md,
      borderRadius: borderRadius.md,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
    },
    styleButtonSelected: { backgroundColor: colors.primary, borderColor: colors.primary },
    styleText: { ...typography.body, fontWeight: '600', color: colors.textPrimary },
    styleTextSelected: { color: colors.white },
    footer: {
      paddingHorizontal: spacing.lg,
      paddingVertical: spacing.md,
      paddingBottom: spacing.xl,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
  });
