import { StyleSheet } from 'react-native';
import { spacing, fontFamily } from '../../../theme/tokens';
import { shadows } from '../../../theme/shadows';
import type { ThemeColors } from '../../../contexts/theme-colors';

export const createStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    container: { flex: 1 },
    background: { flex: 1 },
    safeArea: { flex: 1 },
    scrollContent: {
      flexGrow: 1,
      paddingHorizontal: spacing.lg,
      paddingVertical: spacing.xl,
      alignItems: 'center',
    },
    blob: {
      position: 'absolute',
      width: 256,
      height: 256,
      borderRadius: 128,
    },
    blobGradient: {
      flex: 1,
      borderRadius: 128,
    },
    logoSection: {
      marginTop: spacing['2xl'],
      marginBottom: spacing['2xl'],
    },
    logoContainer: { position: 'relative' },
    logoBackground: {
      width: 80,
      height: 80,
      borderRadius: 24,
      justifyContent: 'center',
      alignItems: 'center',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.5,
      shadowRadius: 24,
      elevation: 12,
    },
    pulseDot: {
      position: 'absolute',
      top: -4,
      right: -4,
      width: 24,
      height: 24,
      borderRadius: 12,
      borderWidth: 2,
    },
    titleSection: {
      alignItems: 'center',
      marginBottom: spacing.lg,
    },
    titleLine: {
      fontFamily: fontFamily.headingCondensed,
      fontSize: 48,
      lineHeight: 52,
      textAlign: 'center',
      color: colors.textPrimary,
      letterSpacing: -1,
    },
    titleAccent: { color: colors.primary },
    subtitle: {
      fontFamily: fontFamily.body,
      fontSize: 16,
      textAlign: 'center',
      lineHeight: 24,
      color: colors.textSecondary,
      marginBottom: spacing['2xl'],
      paddingHorizontal: spacing.md,
    },
    cardsSection: {
      width: '100%',
      marginBottom: spacing['2xl'],
    },
    cardsContainer: {
      width: '100%',
      height: 400,
      position: 'relative',
      alignItems: 'center',
      justifyContent: 'center',
    },
    cardWrapper: { position: 'absolute' },
    floatingCard: {
      width: 224,
      height: 320,
      borderRadius: 24,
      overflow: 'hidden',
      borderWidth: 4,
      borderColor: 'rgba(255, 255, 255, 0.1)',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.3,
      shadowRadius: 24,
      elevation: 12,
    },
    cardImage: { width: '100%', height: '100%' },
    cardGradient: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      height: 120,
    },
    cardInfo: {
      position: 'absolute',
      bottom: 16,
      left: 16,
    },
    cardName: {
      fontFamily: fontFamily.bodySemiBold,
      fontSize: 14,
      color: colors.white,
      opacity: 0.9,
    },
    cardLikeIcon: {
      position: 'absolute',
      top: 16,
      right: 16,
    },
    likeIconGradient: {
      width: 32,
      height: 32,
      borderRadius: 16,
      justifyContent: 'center',
      alignItems: 'center',
    },
    buttonSection: {
      width: '100%',
      marginBottom: spacing.xl,
    },
    buttonContainer: { position: 'relative' },
    buttonGlow: {
      position: 'absolute',
      top: 4,
      left: 4,
      right: 4,
      bottom: -4,
      borderRadius: 16,
      backgroundColor: colors.accent,
      opacity: 0.35,
    },
    getStartedButton: {
      height: 56,
      borderRadius: 16,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: spacing.sm,
      ...shadows.accentButton,
    },
    buttonText: {
      fontFamily: fontFamily.bodySemiBold,
      fontSize: 16,
      color: colors.white,
      letterSpacing: 0.5,
      textTransform: 'uppercase',
    },
    termsText: {
      fontFamily: fontFamily.body,
      fontSize: 12,
      textAlign: 'center',
      lineHeight: 18,
      color: colors.textTertiary,
      paddingHorizontal: spacing.lg,
    },
    loginLinkContainer: {
      marginTop: spacing.md,
      alignItems: 'center',
    },
    loginLinkText: {
      fontFamily: fontFamily.body,
      fontSize: 14,
      color: colors.textSecondary,
    },
    loginLinkAccent: {
      fontFamily: fontFamily.bodySemiBold,
      color: colors.primary,
    },
    webTopBar: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: spacing.xl,
      paddingVertical: spacing.md,
    },
    webTopBarLogo: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
    },
    webTopBarBrand: {
      fontFamily: fontFamily.headingCondensed,
      fontSize: 16,
      fontWeight: '800',
      color: colors.accent,
      letterSpacing: 1.5,
    },
    webLoginButton: {
      paddingHorizontal: spacing.lg,
      paddingVertical: spacing.sm,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: 'rgba(255,255,255,0.05)',
    },
    webLoginText: {
      fontFamily: fontFamily.bodySemiBold,
      fontSize: 14,
      color: colors.textPrimary,
    },
  });
