import { StyleSheet } from 'react-native';
import { typography, borderRadius, fontFamily } from '../../theme/tokens';
import type { ThemeColors } from '../../contexts/theme-colors';

export const createStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    profileImage: {
      width: '100%',
      height: '100%',
    },
    profileGradient: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      height: '45%',
      zIndex: 10,
    },
    matchBadge: {
      position: 'absolute',
      top: 20,
      left: 20,
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.25)',
      zIndex: 20,
    },
    matchBadgeText: {
      color: colors.white,
      fontSize: 13,
      fontWeight: '700',
      letterSpacing: 0.3,
    },
    onlineStatusBadge: {
      position: 'absolute',
      top: 20,
      right: 20,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: 'rgba(255, 255, 255, 0.25)',
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.18)',
      zIndex: 20,
    },
    onlineDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: colors.secondary,
    },
    onlineText: {
      color: colors.white,
      fontSize: 13,
      fontWeight: '600',
    },
    imageIndicatorsContainer: {
      position: 'absolute',
      top: 80,
      left: 20,
      right: 20,
      flexDirection: 'row',
      gap: 6,
      zIndex: 20,
    },
    imageIndicatorTrack: {
      flex: 1,
      height: 3,
      backgroundColor: 'rgba(255, 255, 255, 0.25)',
      borderRadius: 2,
      overflow: 'hidden',
    },
    imageIndicatorFill: {
      width: '100%',
      height: '100%',
    },
    profileInfo: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      padding: 20,
      zIndex: 20,
    },
    profileInfoRow: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      justifyContent: 'space-between',
    },
    profileInfoContent: {
      flex: 1,
    },
    profileHeader: {
      flexDirection: 'row',
      alignItems: 'baseline',
      gap: 10,
      marginBottom: 6,
    },
    profileName: {
      ...typography.h2,
      fontSize: 26,
      color: colors.white,
      fontWeight: '700',
      letterSpacing: -0.3,
      fontFamily: fontFamily.heading,
    },
    profileAge: {
      ...typography.h3,
      fontSize: 22,
      color: colors.white,
      fontWeight: '300',
    },
    verifiedBadge: {
      fontSize: 18,
      color: colors.secondary,
    },
    profileDistance: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      marginBottom: 10,
    },
    profileDistanceText: {
      ...typography.body,
      fontSize: 14,
      color: colors.white,
      opacity: 0.85,
    },
    profileBio: {
      ...typography.body,
      fontSize: 14,
      color: colors.white,
      opacity: 0.85,
      lineHeight: 20,
      marginBottom: 10,
    },
    profileInterests: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
    },
    interestTag: {
      paddingHorizontal: 12,
      paddingVertical: 5,
      backgroundColor: 'rgba(255, 255, 255, 0.15)',
      borderRadius: 20,
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.2)',
    },
    interestTagText: {
      ...typography.bodySmall,
      fontSize: 12,
      color: colors.white,
      fontWeight: '500',
    },
    profileInfoButton: {
      width: 44,
      height: 44,
      backgroundColor: 'rgba(255, 255, 255, 0.15)',
      borderRadius: 22,
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.25)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    profileActionButtons: {
      position: 'absolute',
      bottom: 88,
      left: 0,
      right: 0,
      flexDirection: 'row',
      justifyContent: 'center',
      gap: 14,
      paddingHorizontal: 20,
      zIndex: 30,
    },
    actionButtonReject: {
      width: 60,
      height: 60,
      backgroundColor: 'rgba(255, 255, 255, 0.95)',
      borderRadius: 30,
      borderWidth: 0,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: colors.error,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 12,
      elevation: 6,
    },
    actionButtonSuper: {
      width: 60,
      height: 60,
      borderRadius: 30,
      borderWidth: 0,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.4,
      shadowRadius: 16,
      elevation: 8,
    },
    actionButtonLike: {
      width: 60,
      height: 60,
      borderRadius: 30,
      borderWidth: 0,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: colors.secondary,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.4,
      shadowRadius: 16,
      elevation: 8,
    },
  });
